### ISSUE TITLE
pagraphcontrol-git 1.0.7.r0.g7dc2d21-1 aur build fails.

### ISSUE THREAD

**Issue by takov751** [futpib/pagraphcontrol#10]
aur package building fails from the aur,these error comes up. I believe these are not only arch related errors, as far as i see.
```
476:../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
535:../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
550:../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
553:../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
561:../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
576:../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
589:../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
592:../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
598:../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
629:../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
752:../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
779:../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
935:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1005:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1137:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1244:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1344:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1462:../src/database.cc:351:9: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
1473:../src/database.cc:351:11: error: return-statement with a value, in function returning ‘Nan::NAN_METHOD_RETURN_TYPE’ {aka ‘void’} [-fpermissive]
1809:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
2047:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
2182:../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
2221:../src/macros.h:91:13: error: no matching function for call to ‘v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)’
2292:../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
2307:../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
2310:../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
2316:../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
2347:../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
4337:gyp ERR! build error
4348:node-pre-gyp ERR! build error
3298:   35 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_ERROR, ERROR);
3311:   35 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_ERROR, ERROR);
3324:   35 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_ERROR, ERROR);
3610:   43 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_INTERRUPT, INTERRUPT);
3623:   43 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_INTERRUPT, INTERRUPT);
3636:   43 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_INTERRUPT, INTERRUPT);
3649:   44 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_IOERR, IOERR);
3662:   44 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_IOERR, IOERR);
3675:   44 |     DEFINE_CONSTANT_INTEGER(target, SQLITE_IOERR, IOERR);
4337:gyp ERR! build error
4338:gyp ERR! stack Error: `make` failed with exit code: 2
4339:gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
4340:gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
4341:gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
4342:gyp ERR! System Linux 5.2.14-arch2-1-ARCH
4343:gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3/lib/binding/node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
4344:gyp ERR! cwd /home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3
4345:gyp ERR! node -v v12.10.0
4346:gyp ERR! node-gyp -v v5.0.2
4347:gyp ERR! not ok
4348:node-pre-gyp ERR! build error
4349:node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3/lib/binding/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
4350:node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
4351:node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
4352:node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
4353:node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
4354:node-pre-gyp ERR! System Linux 5.2.14-arch2-1-ARCH
4355:node-pre-gyp ERR! command "/usr/bin/node" "/home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
4356:node-pre-gyp ERR! cwd /home/baldur/.cache/yay/pagraphcontrol-git/src/pagraphcontrol/node_modules/sqlite3
4357:node-pre-gyp ERR! node -v v12.10.0
4358:node-pre-gyp ERR! node-pre-gyp -v v0.11.0
4359:node-pre-gyp ERR! not ok
4363:==> ERROR: A failure occurred in build().
```

**Comment by 3nprob** [comment]
How did you resolve this @takov751 ?
