### ISSUE TITLE
Wrong path used for `gtk-3.0` settings

### ISSUE THREAD

**Issue by sarpik** [futpib/pagraphcontrol#11]
```sh
Error: ENOENT: no such file or directory, open '/home/kipras/home/kipras/.config/gtk-3.0/settings.ini'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at Object.<anonymous> (/usr/lib/pagraphcontrol/resources/app.asar/utils/gtk-theme/index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/kipras/home/kipras/.config/gtk-3.0/settings.ini'
}
(node:140628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [PAClient]. Use emitter.setMaxListeners() to increase limit
(node:140628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [PAClient]. Use emitter.setMaxListeners() to increase limit
(node:140628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PAClient]. Use emitter.setMaxListeners() to increase limit
(node:140628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PAClient]. Use emitter.setMaxListeners() to increase limit
```

notice `path: '/home/kipras/home/kipras/.config/gtk-3.0/settings.ini'`

**Comment by gwario** [comment]
On debian10/cinnamon with code from today, the path seems right:
```
Error: ENOENT: no such file or directory, open '/home/gwario/.config/gtk-3.0/settings.ini'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.<anonymous> (/home/gwario/Downloads/pagraphcontrol/dist/pagraphcontrol-linux-x64/resources/app.asar/utils/gtk-theme/index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/gwario/.config/gtk-3.0/settings.ini'
}
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
```

**Comment by ktosiek** [comment]
Can you try on current master? #31 should have fixed settings loading.
