### ISSUE TITLE
GTK Theme causes crash

### ISSUE THREAD

**Issue by padok** [futpib/pagraphcontrol#2]
```
App threw an error during load
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Object.<anonymous> (/home/louis/git/pagraphcontrol/utils/gtk-theme/index.js:55:29)
    at Object.<anonymous> (/home/louis/git/pagraphcontrol/utils/gtk-theme/index.js:82:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
```

I comment lines 55 to 76 of /home/louis/git/pagraphcontrol/utils/gtk-theme/index.js as workaround.

I'm using the Canta theme (https://github.com/vinceliuice/Canta-theme) on Ubuntu 18.10.

Also thanks for your work that is all what I wanted for years!

**Comment by padok** [comment]
Wow, you guys are fast!
